#!/bin/sh
unset IFS
set -euf

go install github.com/mcandre/slick/cmd/slick@v0.0.7
go install github.com/mcandre/stank/...@v0.0.27
go install mvdan.cc/sh/v3/cmd/shfmt@v3.7.0
go mod tidy

pip install --user pipenv
pip3 install -r requirements.txt
