---
name: "Lint"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
jobs:
  Lint:
    runs-on: "ubuntu-24.04"
    env:
      GOPATH: "/home/runner/go"
    steps:
    - uses: "actions/setup-go@v5"
      with:
        go-version: "1.24.0"
    - uses: "actions/checkout@v4"
    - run: |
        sudo apt-get update
        sudo apt-get install -y curl python3-venv shellcheck
        ./install
        ./build lint
